### ISSUE TITLE
Is this project still active? 

### ISSUE THREAD

**Issue by marwan-at-work** [elliots/protoc-gen-twirp_swagger#11]
@elliots I'm wondering if this project is still active, as I plan to use it for production purposes. I opened a PR and I also know that Twirp v6 might require this project to be updated as URL paths might be changed, so I plan on also making sure this project is updated. Thank you

**Comment by elliots** [comment]
Hi, I hadn't noticed the pull request, it has been merged now. It is active enough if I notice the issues/PRs, but I am not currently using it myself. If you want push access I'd be happy to grant it?

**Comment by marwan-at-work** [comment]
@elliots thank you for the prompt response! I'd be happy to take push access. I'll try to get to know the codebase first before jumping into anything. I like Twirp so I'd be happy to keep tooling around in good shape. 

Thanks
